# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sq6Zp2fCpUpyyJv5c2hPIPhbwkojzte0
"""

!rm -f violence_action_classifier.pth

!git clone https://github.com/chaudharyabdullaht-debug/Computer-Vision.git
!ls -la Computer-Vision

from google.colab import files
uploaded = files.upload()  # Select your violence_action_classifier.pth file

import torch
import torch.nn as nn

# 1. Define the ActionClassifier1D architecture
class ActionClassifier1D(nn.Module):
    def __init__(self, num_classes=2):
        super(ActionClassifier1D, self).__init__()
        self.net = nn.Sequential(
            nn.Conv1d(in_channels=51, out_channels=64, kernel_size=3, padding=1),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2),
            nn.Conv1d(in_channels=64, out_channels=128, kernel_size=3, padding=1),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2),
            nn.AdaptiveAvgPool1d(1),
            nn.Flatten(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(64, num_classes)
        )

    def forward(self, x):
        if x.dim() == 4:
            b, frames, joints, coords = x.shape
            x = x.view(b, frames, joints * coords).transpose(1, 2)
        return self.net(x)

# 2. Instantiate the model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = ActionClassifier1D().to(device)

# 3. Save weights after model training completes
torch.save(model.state_dict(), "violence_action_classifier.pth")

from google.colab import files
uploaded = files.upload()  # Select violence_action_classifier.pth when prompted

import os
import torch
from google.colab import drive

# 1. Ensure Google Drive is mounted
drive.mount('/content/drive')

# 2. Search Drive for any .pth file
drive_pth_files = []
for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file.endswith('.pth'):
            drive_pth_files.append(os.path.join(root, file))

if not drive_pth_files:
    print("❌ No .pth file found in Google Drive. Upload 'violence_action_classifier.pth' to your Drive first.")
else:
    # 3. Load the matched weights file
    weights_path = drive_pth_files[0]
    print(f"✅ Found weights file at: {weights_path}")

    model.load_state_dict(torch.load(weights_path, map_location=device))
    model.eval()
    print("🚀 Model successfully loaded!")

import cv2
import torch
import numpy as np
from ultralytics import YOLO

# 1. Load YOLOv8 Pose model
pose_model = YOLO("yolov8n-pose.pt")

def predict_video_action(video_path, sequence_length=48):
    cap = cv2.VideoCapture(video_path)
    frames_keypoints = []

    while cap.isOpened() and len(frames_keypoints) < sequence_length:
        ret, frame = cap.read()
        if not ret:
            break

        # Pose estimation frame by frame
        results = pose_model(frame, verbose=False)

        # Extract primary person keypoints (17 joints x 3 [x, y, conf])
        if results[0].keypoints is not None and len(results[0].keypoints) > 0:
            kp = results[0].keypoints.data[0].cpu().numpy()  # Shape: (17, 3)
        else:
            kp = np.zeros((17, 3))

        frames_keypoints.append(kp)

    cap.release()

    # Zero-padding if sequence length is under 48 frames
    while len(frames_keypoints) < sequence_length:
        frames_keypoints.append(np.zeros((17, 3)))

    # Convert sequence to PyTorch Tensor -> Shape: (1, 48, 17, 3)
    sequence_array = np.array(frames_keypoints, dtype=np.float32)
    input_tensor = torch.tensor(sequence_array).unsqueeze(0).to(device)

    # 2. Run classification
    with torch.no_grad():
        outputs = model(input_tensor)
        probs = torch.softmax(outputs, dim=1)
        pred_class = torch.argmax(probs, dim=1).item()
        confidence = probs[0][pred_class].item() * 100

    classes = ["Non-Violent", "Violent"]
    return classes[pred_class], confidence

# Execute on a sample video clip
label, conf = predict_video_action("test_video.mp4")
print(f"Prediction: {label} ({conf:.2f}% confidence)")

import cv2
import torch
import numpy as np
from ultralytics import YOLO

def process_and_annotate_video(input_video_path, output_video_path, sequence_length=48):
    # 1. Initialize YOLOv8 Pose
    pose_model = YOLO("yolov8n-pose.pt")

    cap = cv2.VideoCapture(input_video_path)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(cap.get(cv2.CAP_PROP_FPS)) or 30

    # 2. Setup Video Writer
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

    kp_sequence = []
    label = "Analyzing..."
    confidence = 0.0

    print(f"Processing video: {input_video_path}...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Run pose detection and plot keypoint skeletons
        results = pose_model(frame, verbose=False)
        annotated_frame = results[0].plot()

        # Extract keypoints (17 joints x 3)
        if results[0].keypoints is not None and len(results[0].keypoints) > 0:
            kp = results[0].keypoints.data[0].cpu().numpy()
        else:
            kp = np.zeros((17, 3))

        kp_sequence.append(kp)

        # Maintain a sliding window buffer of the latest 48 frames
        if len(kp_sequence) > sequence_length:
            kp_sequence.pop(0)

        # Run 1D-CNN classification when sequence buffer is filled
        if len(kp_sequence) == sequence_length:
            sequence_array = np.array(kp_sequence, dtype=np.float32)
            input_tensor = torch.tensor(sequence_array).unsqueeze(0).to(device)

            with torch.no_grad():
                outputs = model(input_tensor)
                probs = torch.softmax(outputs, dim=1)
                pred_class = torch.argmax(probs, dim=1).item()
                confidence = probs[0][pred_class].item() * 100

            classes = ["Non-Violent", "Violent"]
            label = classes[pred_class]

        # Render prediction status banner overlay
        banner_color = (0, 0, 255) if label == "Violent" else (0, 255, 0) if label == "Non-Violent" else (255, 255, 255)
        display_text = f"{label} ({confidence:.1f}%)" if label != "Analyzing..." else label

        # Draw translucent background bar
        overlay = annotated_frame.copy()
        cv2.rectangle(overlay, (20, 20), (380, 70), (0, 0, 0), -1)
        cv2.addWeighted(overlay, 0.6, annotated_frame, 0.4, 0, annotated_frame)

        # Draw text label
        cv2.putText(annotated_frame, display_text, (35, 55),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, banner_color, 2, cv2.LINE_AA)

        out.write(annotated_frame)

    cap.release()
    out.release()
    print(f" Output successfully exported to: {output_video_path}")

# Run pipeline and save directly to Google Drive
output_path = "/content/drive/MyDrive/annotated_output.mp4"
process_and_annotate_video("test_video.mp4", output_path)

from google.colab import files

# 1. Select and upload your pre-recorded video file (e.g., .mp4, .avi, .mov)
uploaded = files.upload()

# Automatically grab the name of the uploaded video file
input_video_name = list(uploaded.keys())[0]
print(f"Loaded file: {input_video_name}")

# 2. Process your uploaded video through the violence detection pipeline
output_drive_path = "/content/drive/MyDrive/uploaded_video_result.mp4"
process_and_annotate_video(input_video_name, output_drive_path)

import cv2
import numpy as np
import torch
from ultralytics import YOLO

pose_model = YOLO("yolov8n-pose.pt")

def extract_training_sequences(video_path, label, sequence_length=48, stride=12):
    cap = cv2.VideoCapture(video_path)
    raw_keypoints = []

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        results = pose_model(frame, verbose=False)

        if results[0].keypoints is not None and len(results[0].keypoints) > 0:
            kp = results[0].keypoints.data[0].cpu().numpy()  # (17, 3)
        else:
            kp = np.zeros((17, 3))

        raw_keypoints.append(kp)

    cap.release()

    # Generate sliding window sequences
    sequences, labels = [], []
    for i in range(0, len(raw_keypoints) - sequence_length + 1, stride):
        seq = raw_keypoints[i : i + sequence_length]
        sequences.append(seq)
        labels.append(label)

    return np.array(sequences, dtype=np.float32), np.array(labels, dtype=np.int64)

# Set label: 1 for Violent, 0 for Non-Violent
X_data, y_data = extract_training_sequences("whatsapp_merged_videos.mp4", label=1)
print(f"Extracted {len(X_data)} sequence samples for fine-tuning.")

import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

# 1. Create PyTorch DataLoader
dataset = TensorDataset(torch.tensor(X_data), torch.tensor(y_data))
dataloader = DataLoader(dataset, batch_size=8, shuffle=True)

# 2. Setup Optimizer with lower learning rate for fine-tuning
model.train()
criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

# 3. Fine-tuning loop
epochs = 15
print("Starting fine-tuning...")

for epoch in range(epochs):
    total_loss = 0.0
    for inputs, targets in dataloader:
        inputs, targets = inputs.to(device), targets.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(dataloader)
    print(f"Epoch [{epoch+1}/{epochs}] - Loss: {avg_loss:.4f}")

# 4. Save fine-tuned weights back to Google Drive
save_path = "/content/drive/MyDrive/violence_action_classifier.pth"
torch.save(model.state_dict(), save_path)
model.eval()

print(f" Fine-tuning complete! Updated weights saved to: {save_path}")

# Run annotated inference with your updated weights
finetuned_output_path = "/content/drive/MyDrive/finetuned_video_result.mp4"
process_and_annotate_video("whatsapp_merged_videos.mp4", finetuned_output_path)

# Create dummy input shape: (batch_size=1, sequence_length=48, joints=17, coords=3)
dummy_input = torch.randn(1, 48, 17, 3).to(device)
onnx_path = "/content/drive/MyDrive/violence_classifier.onnx"

torch.onnx.export(
    model,
    dummy_input,
    onnx_path,
    export_params=True,
    opset_version=12,
    input_names=["keypoints"],
    output_names=["logits"],
    dynamic_axes={"keypoints": {0: "batch_size"}, "logits": {0: "batch_size"}}
)

print(f"📦 Fine-tuned model exported to ONNX format at: {onnx_path}")

# 1. Install missing ONNX dependencies
!pip install onnx onnxscript

# 2. Export the fine-tuned model to ONNX
import torch

dummy_input = torch.randn(1, 48, 17, 3).to(device)
onnx_path = "/content/drive/MyDrive/violence_classifier.onnx"

torch.onnx.export(
    model,
    dummy_input,
    onnx_path,
    export_params=True,
    opset_version=14,
    input_names=["keypoints"],
    output_names=["logits"],
    dynamic_axes={"keypoints": {0: "batch_size"}, "logits": {0: "batch_size"}}
)

print(f"📦 Fine-tuned model exported successfully to: {onnx_path}")

!pip install onnxruntime

import numpy as np
import onnxruntime as ort

# 1. Initialize ONNX runtime session
onnx_path = "/content/drive/MyDrive/violence_classifier.onnx"
session = ort.InferenceSession(onnx_path)

# 2. Get input/output layer names
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name

# 3. Pass keypoint sequence through ONNX session (1, 48, 17, 3)
sample_keypoints = np.random.randn(1, 48, 17, 3).astype(np.float32)
logits = session.run([output_name], {input_name: sample_keypoints})[0]

# 4. Compute confidence probabilities
probs = np.exp(logits) / np.sum(np.exp(logits), axis=1, keepdims=True)
pred_class = np.argmax(probs, axis=1)[0]

classes = ["Non-Violent", "Violent"]
print(f"⚡ ONNX Output: {classes[pred_class]} ({probs[0][pred_class]*100:.2f}% confidence)")

import cv2
from ultralytics import YOLO

def process_video_onnx(input_path, output_path, onnx_model_path):
    session = ort.InferenceSession(onnx_model_path)
    input_name = session.get_inputs()[0].name
    output_name = session.get_outputs()[0].name

    pose_model = YOLO("yolov8n-pose.pt")
    cap = cv2.VideoCapture(input_path)

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(cap.get(cv2.CAP_PROP_FPS)) or 30

    out = cv2.VideoWriter(output_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (width, height))
    kp_sequence = []

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        results = pose_model(frame, verbose=False)
        annotated_frame = results[0].plot()

        if results[0].keypoints is not None and len(results[0].keypoints) > 0:
            kp = results[0].keypoints.data[0].cpu().numpy()
        else:
            kp = np.zeros((17, 3))

        kp_sequence.append(kp)
        if len(kp_sequence) > 48:
            kp_sequence.pop(0)

        label, conf = "Analyzing...", 0.0
        if len(kp_sequence) == 48:
            input_data = np.array(kp_sequence, dtype=np.float32)[np.newaxis, ...]
            logits = session.run([output_name], {input_name: input_data})[0]
            probs = np.exp(logits) / np.sum(np.exp(logits), axis=1, keepdims=True)
            pred_class = np.argmax(probs, axis=1)[0]
            label = ["Non-Violent", "Violent"][pred_class]
            conf = probs[0][pred_class] * 100

        color = (0, 0, 255) if label == "Violent" else (0, 255, 0)
        cv2.putText(annotated_frame, f"{label} ({conf:.1f}%)", (30, 50),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2)
        out.write(annotated_frame)

    cap.release()
    out.release()
    print("✅ ONNX processing complete!")

# Test lightweight pipeline
process_video_onnx("whatsapp_merged_videos.mp4",
                   "/content/drive/MyDrive/onnx_fast_output.mp4",
                   "/content/drive/MyDrive/violence_classifier.onnx")

from google.colab import files

files.download("/content/drive/MyDrive/onnx_fast_output.mp4")

import os

# Create directory structure for your dataset
os.makedirs("dataset/violent", exist_ok=True)
os.makedirs("dataset/non_violent", exist_ok=True)

print("📁 Folders created!")
print("1. Upload violent videos into: /content/dataset/violent")
print("2. Upload normal/non-violent videos into: /content/dataset/non_violent")

import os
import cv2
import numpy as np
import torch
from ultralytics import YOLO

pose_model = YOLO("yolov8n-pose.pt")

def extract_dataset_from_folders(dataset_path="dataset", sequence_length=48, stride=12):
    X, y = [], []
    classes = {'non_violent': 0, 'violent': 1}

    for class_name, label in classes.items():
        folder_path = os.path.join(dataset_path, class_name)
        if not os.path.exists(folder_path):
            continue

        video_files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.mp4', '.avi', '.mov', '.webm'))]
        print(f"🔍 Extracting features from '{class_name}' ({len(video_files)} videos)...")

        for video_file in video_files:
            video_path = os.path.join(folder_path, video_file)
            cap = cv2.VideoCapture(video_path)
            raw_keypoints = []

            while cap.isOpened():
                ret, frame = cap.read()
                if not ret:
                    break
                results = pose_model(frame, verbose=False)

                if results[0].keypoints is not None and len(results[0].keypoints) > 0:
                    kp = results[0].keypoints.data[0].cpu().numpy()  # Shape: (17, 3)
                else:
                    kp = np.zeros((17, 3))

                raw_keypoints.append(kp)
            cap.release()

            # Sliding window sequence extraction
            for i in range(0, len(raw_keypoints) - sequence_length + 1, stride):
                X.append(raw_keypoints[i : i + sequence_length])
                y.append(label)

    return np.array(X, dtype=np.float32), np.array(y, dtype=np.int64)

# Run feature extraction on uploaded videos
X_data, y_data = extract_dataset_from_folders("dataset")
print(f" Total training sequences created: {len(X_data)}")

import os

violent_files = os.listdir("dataset/violent") if os.path.exists("dataset/violent") else []
non_violent_files = os.listdir("dataset/non_violent") if os.path.exists("dataset/non_violent") else []

print(f"📹 Violent videos found: {len(violent_files)} -> {violent_files}")
print(f"📹 Non-Violent videos found: {len(non_violent_files)} -> {non_violent_files}")

import os
import shutil

# Make sure directories exist
os.makedirs("dataset/violent", exist_ok=True)
os.makedirs("dataset/non_violent", exist_ok=True)

# 1. Copy your existing video into 'violent' directory
if os.path.exists("whatsapp_merged_videos.mp4"):
    shutil.copy("whatsapp_merged_videos.mp4", "dataset/violent/whatsapp_merged_videos.mp4")
    print(" Copy complete: Added whatsapp_merged_videos.mp4 to dataset/violent/")

# 2. Re-run feature extraction with safety check
X_data, y_data = extract_dataset_from_folders("dataset")

if len(X_data) == 0:
    print("❌ X_data is still empty! Please upload at least one video into /content/dataset/violent or /content/dataset/non_violent via the Colab sidebar.")
else:
    print(f"✅ Successfully loaded {len(X_data)} sequences into X_data!")

from sklearn.model_selection import train_test_split

# Safe split for small datasets
if len(X_data) > 0:
    # If dataset is very small, use test_size=0.1 or disable stratify
    use_stratify = y_data if len(set(y_data)) > 1 and len(y_data) >= 10 else None

    X_train, X_val, y_train, y_val = train_test_split(
        X_data, y_data, test_size=0.2, random_state=42, stratify=use_stratify
    )
    print(f" Training samples: {len(X_train)} | Validation samples: {len(X_val)}")

import os
import cv2
import numpy as np
import torch
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from ultralytics import YOLO
from google.colab import files

# 1. Upload your new violence video file
print(" Please select and upload your new violence video:")
uploaded = files.upload()
new_video_path = list(uploaded.keys())[0]
print(f"Uploaded: {new_video_path}")

# 2. Extract keypoint sequences from the new video (Label = 1 for Violent)
pose_model = YOLO("yolov8n-pose.pt")

def extract_single_video_sequences(video_path, label=1, sequence_length=48, stride=6):
    cap = cv2.VideoCapture(video_path)
    raw_keypoints = []

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        results = pose_model(frame, verbose=False)

        if results[0].keypoints is not None and len(results[0].keypoints) > 0:
            kp = results[0].keypoints.data[0].cpu().numpy()  # (17, 3)
        else:
            kp = np.zeros((17, 3))

        raw_keypoints.append(kp)

    cap.release()

    sequences = []
    for i in range(0, len(raw_keypoints) - sequence_length + 1, stride):
        sequences.append(raw_keypoints[i : i + sequence_length])

    return np.array(sequences, dtype=np.float32), np.full(len(sequences), label, dtype=np.int64)

# Generate fine-tuning dataset
X_new, y_new = extract_single_video_sequences(new_video_path, label=1)
print(f"✅ Extracted {len(X_new)} violence action sequences!")

# 3. Fine-tune the PyTorch model with a small learning rate
dataset = TensorDataset(torch.tensor(X_new), torch.tensor(y_new))
dataloader = DataLoader(dataset, batch_size=8, shuffle=True)

model.train()
criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

epochs = 15
print("🔥 Training model on the new video...")

for epoch in range(epochs):
    total_loss = 0.0
    for inputs, targets in dataloader:
        inputs, targets = inputs.to(device), targets.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(dataloader)
    print(f"Epoch [{epoch+1}/{epochs}] - Fine-tuning Loss: {avg_loss:.4f}")

# 4. Save updated PyTorch weights
pth_save_path = "/content/drive/MyDrive/violence_action_classifier.pth"
torch.save(model.state_dict(), pth_save_path)
model.eval()
print(f" Updated PyTorch model saved to: {pth_save_path}")

# Export the fine-tuned PyTorch model to ONNX
dummy_input = torch.randn(1, 48, 17, 3).to(device)
onnx_path = "/content/drive/MyDrive/violence_classifier.onnx"

torch.onnx.export(
    model,
    dummy_input,
    onnx_path,
    export_params=True,
    opset_version=14,
    input_names=["keypoints"],
    output_names=["logits"],
    dynamic_axes={"keypoints": {0: "batch_size"}, "logits": {0: "batch_size"}}
)

print(f"📦 Fine-tuned model re-exported successfully to ONNX at: {onnx_path}")

output_annotated_path = "/content/drive/MyDrive/new_video_result.mp4"

# Process video using the updated ONNX model
process_video_onnx(new_video_path, output_annotated_path, onnx_path)

import cv2
import numpy as np
import onnxruntime as ort
from ultralytics import YOLO
from google.colab import files
from IPython.display import HTML
from base64 import b64encode

# 1. Upload your new test video
print("📁 Select and upload your test video file:")
uploaded = files.upload()
input_video_path = list(uploaded.keys())[0]
output_video_path = "/content/drive/MyDrive/fight_detection_output.mp4"
onnx_model_path = "/content/drive/MyDrive/violence_classifier.onnx"

# 2. Define the fight detection processor
def detect_fights_in_video(input_path, output_path, model_path, seq_len=48):
    # Initialize ONNX runtime and Pose model
    session = ort.InferenceSession(model_path)
    input_name = session.get_inputs()[0].name
    output_name = session.get_outputs()[0].name
    pose_model = YOLO("yolov8n-pose.pt")

    cap = cv2.VideoCapture(input_path)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(cap.get(cv2.CAP_PROP_FPS)) or 30

    out = cv2.VideoWriter(output_path, cv2.VideoWriter_fourcc(*'mp4v'), fps, (width, height))
    kp_sequence = []

    print("🎥 Processing video frames for fight detection...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # Pose Estimation
        results = pose_model(frame, verbose=False)
        annotated_frame = results[0].plot()

        if results[0].keypoints is not None and len(results[0].keypoints) > 0:
            kp = results[0].keypoints.data[0].cpu().numpy()  # (17, 3)
        else:
            kp = np.zeros((17, 3))

        kp_sequence.append(kp)
        if len(kp_sequence) > seq_len:
            kp_sequence.pop(0)

        # Classify sequence when 48 frames are buffered
        status_text = "Analyzing..."
        conf_score = 0.0
        is_fight = False

        if len(kp_sequence) == seq_len:
            input_tensor = np.array(kp_sequence, dtype=np.float32)[np.newaxis, ...]
            logits = session.run([output_name], {input_name: input_tensor})[0]

            # Softmax calculation
            exp_logits = np.exp(logits - np.max(logits))
            probs = exp_logits / np.sum(exp_logits, axis=1, keepdims=True)
            pred_class = np.argmax(probs, axis=1)[0]

            is_fight = (pred_class == 1)
            status_text = "🚨 FIGHT DETECTED" if is_fight else "✅ NORMAL / NO FIGHT"
            conf_score = probs[0][pred_class] * 100

        # Draw Top Status Banner
        banner_color = (0, 0, 220) if is_fight else (0, 180, 0)
        cv2.rectangle(annotated_frame, (0, 0), (width, 60), banner_color, -1)

        display_label = f"{status_text} ({conf_score:.1f}%)" if status_text != "Analyzing..." else status_text
        cv2.putText(annotated_frame, display_label, (20, 40),
                    cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 255, 255), 3)

        out.write(annotated_frame)

    cap.release()
    out.release()
    print(f"✅ Processing finished! Output saved to: {output_path}")

# 3. Execute fight detection pipeline
detect_fights_in_video(input_video_path, output_video_path, onnx_model_path)

files.download(output_video_path)

